# Noxfort Monitor™ is an open-source industrial telemetry, observability, and incident response orchestration system.
# Copyright (C) 2026 Gabriel Moraes - Noxfort Systems
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# File: mosquitto/config/mosquitto.conf
# Author: Gabriel Moraes
# Date: 2026-01-15

# =================================================================
# General Configuration
# =================================================================

pid_file mosquitto/data/mosquitto.pid

# =================================================================
# Persistence
# =================================================================

# Save persistent message data to disk (true/false).
persistence true

# Location for persistent database (relative to project root).
persistence_location mosquitto/data/

# =================================================================
# Logging
# =================================================================

log_dest file mosquitto/log/mosquitto.log
log_dest stdout

log_type error
log_type warning
log_type notice
log_type information

# =================================================================
# Listeners & Security
# =================================================================

# Listen on port 1883 (Standard MQTT) on all interfaces.
listener 1883

# Allow anonymous connections (No Username/Password).
# REQUIRED because our Go client currently sends empty credentials.
# In production, set this to false and use a password file.
allow_anonymous true